# Generated by Django 5.1.7 on 2025-05-02 14:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('album_facebook_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollageSession',
            fields=[
                ('session_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sesión de Collage',
                'verbose_name_plural': 'Sesiones de Collage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollageTemplate',
            fields=[
                ('template_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='collage/backgrounds/')),
                ('background_size', models.CharField(default='cover', max_length=20)),
                ('background_position', models.CharField(default='center', max_length=20)),
                ('background_repeat', models.CharField(default='no-repeat', max_length=20)),
                ('template_data', models.TextField(help_text='Datos completos de la plantilla en formato JSON')),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Collage',
                'verbose_name_plural': 'Plantillas de Collage',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(db_index=True, help_text='Número de cédula o documento de identidad', max_length=20, unique=True, verbose_name='Cédula')),
                ('fechaNacimiento', models.DateField(help_text='Fecha de nacimiento del cliente', verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(help_text='Dirección completa del cliente', max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(db_index=True, help_text='Correo electrónico del cliente', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CollageResult',
            fields=[
                ('collage_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='collage/results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='usuarios.collagesession')),
            ],
            options={
                'verbose_name': 'Resultado de Collage',
                'verbose_name_plural': 'Resultados de Collage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collagesession',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='usuarios.collagetemplate'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o título del evento', max_length=100, verbose_name='Nombre del evento')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora programada para el evento', verbose_name='Fecha y hora del evento')),
                ('servicios', multiselectfield.db.fields.MultiSelectField(choices=[('photobook', 'Photobook'), ('foto_tradicional', 'Foto tradicional'), ('video', 'Video'), ('cabina_360', 'Cabina 360'), ('cabina_fotos', 'Cabina fotos'), ('drone', 'Drone'), ('clip_inicio', 'Clip de inicio')], help_text='Servicios contratados para el evento', max_length=100, verbose_name='Servicios')),
                ('direccion', models.CharField(help_text='Dirección completa donde se realizará el evento', max_length=255, verbose_name='Dirección del evento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Selecciona la categoría del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoriaevento', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(help_text='Cliente asociado al evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Configurar_Photobooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_bienvenida', models.CharField(default='¡Bienvenidos a nuestro photobooth!', max_length=255)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='photobooth/fondos/')),
                ('color_texto', models.CharField(default='#000000', max_length=7)),
                ('tamano_texto', models.IntegerField(default=24)),
                ('tipo_letra', models.CharField(default='Arial', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('camera_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de cámara seleccionada')),
                ('resolucion_camara', models.CharField(choices=[('640x480', '640x480 (VGA)'), ('1280x720', '1280x720 (HD)'), ('1920x1080', '1920x1080 (Full HD)'), ('3840x2160', '3840x2160 (4K)')], default='1280x720', max_length=20, verbose_name='Resolución de cámara')),
                ('balance_blancos', models.CharField(choices=[('auto', 'Automático'), ('cloudy', 'Nublado'), ('sunny', 'Soleado'), ('fluorescent', 'Fluorescente'), ('incandescent', 'Incandescente')], default='auto', max_length=20, verbose_name='Balance de blancos')),
                ('max_fotos', models.IntegerField(choices=[(1, '1 foto'), (2, '2 fotos'), (4, '4 fotos'), (5, '5 fotos')], default=4)),
                ('permitir_personalizar', models.BooleanField(default=True, help_text='Permitir a los usuarios mover y redimensionar fotos')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_photobooth', to='usuarios.evento')),
            ],
        ),
        migrations.AddField(
            model_name='collagetemplate',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_templates', to='usuarios.evento'),
        ),
        migrations.AddField(
            model_name='collagesession',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_sessions', to='usuarios.evento'),
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='usuarios.evento')),
                ('invitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='usuarios.invitado')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoboothConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_bienvenida', models.CharField(default='¡Bienvenidos al photobooth!', max_length=200)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='photobooth/fondos/')),
                ('color_texto', models.CharField(default='#000000', max_length=20)),
                ('tamano_texto', models.IntegerField(default=24)),
                ('tipo_letra', models.CharField(default='Arial', max_length=50)),
                ('permitir_personalizar', models.BooleanField(default=False)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_config', to='usuarios.evento')),
                ('plantilla_collage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_configs', to='usuarios.collagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoboothSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_sessions', to='usuarios.evento')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.collagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField(help_text='Índice del marco en la plantilla')),
                ('image', models.ImageField(upload_to='collage/session_photos/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='usuarios.collagesession')),
            ],
            options={
                'verbose_name': 'Foto de Sesión',
                'verbose_name_plural': 'Fotos de Sesión',
                'ordering': ['session', 'frame_index'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cedula'], name='usuarios_cl_cedula_f55efd_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['correo'], name='usuarios_cl_correo_179f36_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='usuarios_cl_search__108e6a_gin'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_hora'], name='usuarios_ev_fecha_h_e4dd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['cliente'], name='usuarios_ev_cliente_4edfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='usuarios_ev_search__de3133_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionphoto',
            unique_together={('session', 'frame_index')},
        ),
    ]
