# Generated by Django 5.1.5 on 2025-05-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaevento",
            name="album_facebook_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="img",
            field=models.ImageField(upload_to="imagenes/"),
        ),
    ]
