# Generated by Django 5.1.5 on 2025-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fotografia",
            name="invitado",
        ),
        migrations.AddField(
            model_name="fotografia",
            name="invitados",
            field=models.ManyToManyField(
                blank=True, related_name="fotografias", to="usuarios.invitado"
            ),
        ),
    ]
