# Generated by Django 5.1.5 on 2025-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='invitado',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='invitado',
            field=models.ManyToManyField(null=True, related_name='fotografias', to='usuarios.invitado'),
        ),
    ]
