# Generated by Django 5.1.5 on 2025-03-22 18:58

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('album_facebook_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('photobook', 'Photobook'), ('foto_tradicional', 'Foto tradicional'), ('video', 'Video'), ('cabina_360', 'Cabina 360'), ('cabina_fotos', 'Cabina fotos'), ('drone', 'Drone'), ('clip_inicio', 'Clip de inicio')], max_length=100, verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoriaevento', verbose_name='Categoría'),
        ),
    ]
