# Generated by Django 5.1.5 on 2025-05-31 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'El apellido debe ser de al menos 3 caracteres')], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe ser de al menos 3 caracteres')], verbose_name='Nombre'),
        ),
    ]
