# Generated by Django 5.1.6 on 2025-06-01 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurar_photobooth',
            name='balance_blancos',
        ),
        migrations.RemoveField(
            model_name='photoboothconfig',
            name='balance_blancos',
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='apertura',
            field=models.CharField(blank=True, default='f/5.6', help_text='Ej: f/2.8, f/4, f/5.6', max_length=10, null=True, verbose_name='Apertura (f-stop)'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='calidad_imagen',
            field=models.CharField(choices=[('RAW', 'RAW (NEF)'), ('JPEG_FINE', 'JPEG Fine'), ('JPEG_NORMAL', 'JPEG Normal'), ('RAW_JPEG', 'RAW + JPEG')], default='JPEG_FINE', max_length=20, verbose_name='Calidad de imagen'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='modo_disparo',
            field=models.CharField(blank=True, choices=[('M', 'Manual'), ('A', 'Prioridad de Apertura'), ('S', 'Prioridad de Obturación'), ('P', 'Programa')], default='M', max_length=20, null=True, verbose_name='Modo de disparo'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='modo_enfoque',
            field=models.CharField(choices=[('AF-S', 'AF Simple (AF-S)'), ('AF-C', 'AF Continuo (AF-C)'), ('MF', 'Manual (MF)')], default='AF-S', max_length=20, verbose_name='Modo de enfoque'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='nikon_camera_model',
            field=models.CharField(blank=True, help_text='Modelo detectado automáticamente', max_length=100, null=True, verbose_name='Modelo de cámara Nikon'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='nivel_iluminacion',
            field=models.IntegerField(default=50, help_text='Ajuste de brillo/iluminación de 0 a 100', validators=[django.core.validators.MinValueValidator(0, message='El nivel mínimo de iluminación es 0'), django.core.validators.MaxValueValidator(100, message='El nivel máximo de iluminación es 100')], verbose_name='Nivel de iluminación (%)'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='qdslr_server_port',
            field=models.IntegerField(default=4757, help_text='Puerto donde corre el servidor (default: 4757)', verbose_name='Puerto del servidor qDslrDashboard'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='tipo_camara',
            field=models.CharField(choices=[('webcam', 'Cámara Web'), ('nikon_dslr', 'Nikon DSLR/Mirrorless')], default='webcam', help_text='Tipo de cámara a utilizar', max_length=20, verbose_name='Tipo de cámara'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='velocidad_obturacion',
            field=models.CharField(blank=True, default='1/125', help_text='Ej: 1/125, 1/60, 1/30', max_length=20, null=True, verbose_name='Velocidad de obturación'),
        ),
    ]
