# Generated by Django 5.1.5 on 2025-03-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
