# Generated by Django 5.1.6 on 2025-05-03 03:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoboothconfig',
            options={'verbose_name': 'Configuración de Photobooth', 'verbose_name_plural': 'Configuraciones de Photobooth'},
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el photobooth está activo para este evento', verbose_name='Photobooth activo'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='balance_blancos',
            field=models.CharField(choices=[('auto', 'Automático'), ('cloudy', 'Nublado'), ('sunny', 'Soleado'), ('fluorescent', 'Fluorescente'), ('incandescent', 'Incandescente')], default='auto', help_text='Ajuste del balance de blancos de la cámara', max_length=20, verbose_name='Balance de blancos'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='calidad_impresion',
            field=models.CharField(choices=[('draft', 'Borrador'), ('normal', 'Normal'), ('high', 'Alta'), ('best', 'Máxima')], default='high', help_text='Calidad de impresión para los collages', max_length=20, verbose_name='Calidad de impresión'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='camera_id',
            field=models.CharField(blank=True, help_text='Identificador de la cámara web a utilizar', max_length=255, null=True, verbose_name='ID de cámara seleccionada'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='copias_impresion',
            field=models.IntegerField(default=1, help_text='Número de copias a imprimir por defecto', validators=[django.core.validators.MinValueValidator(1, message='Debe imprimir al menos 1 copia'), django.core.validators.MaxValueValidator(10, message='Máximo 10 copias por impresión')], verbose_name='Copias a imprimir'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='imprimir_automaticamente',
            field=models.BooleanField(default=False, help_text='Si está activado, imprime automáticamente al finalizar el collage', verbose_name='Imprimir automáticamente'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='iso_valor',
            field=models.IntegerField(default=100, help_text='Sensibilidad ISO de la cámara', validators=[django.core.validators.MinValueValidator(100, message='El ISO mínimo es 100'), django.core.validators.MaxValueValidator(3200, message='El ISO máximo es 3200')], verbose_name='Valor ISO'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='paper_size',
            field=models.CharField(choices=[('10x15', '10x15 cm (4x6 pulgadas)'), ('13x18', '13x18 cm (5x7 pulgadas)'), ('15x20', '15x20 cm (6x8 pulgadas)'), ('20x25', '20x25 cm (8x10 pulgadas)'), ('A4', 'A4 (21x29.7 cm)'), ('Letter', 'Letter (8.5x11 pulgadas)')], default='10x15', help_text='Tamaño del papel para impresión de collages', max_length=50, verbose_name='Tamaño de papel'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='printer_name',
            field=models.CharField(blank=True, help_text='Nombre de la impresora a utilizar para imprimir los collages', max_length=255, null=True, verbose_name='Impresora seleccionada'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='resolucion_camara',
            field=models.CharField(choices=[('640x480', '640x480 (VGA)'), ('1280x720', '1280x720 (HD)'), ('1920x1080', '1920x1080 (Full HD)'), ('3840x2160', '3840x2160 (4K)')], default='1280x720', help_text='Resolución para capturar las fotos', max_length=20, verbose_name='Resolución de cámara'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='tiempo_cuenta_regresiva',
            field=models.IntegerField(default=3, help_text='Cuenta regresiva antes de tomar cada foto', validators=[django.core.validators.MinValueValidator(1, message='La cuenta regresiva mínima es 1 segundo'), django.core.validators.MaxValueValidator(10, message='La cuenta regresiva máxima es 10 segundos')], verbose_name='Tiempo de cuenta regresiva'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='tiempo_entre_fotos',
            field=models.IntegerField(default=3, help_text='Intervalo de tiempo entre cada foto durante la sesión', validators=[django.core.validators.MinValueValidator(1, message='El tiempo mínimo entre fotos es 1 segundo'), django.core.validators.MaxValueValidator(20, message='El tiempo máximo entre fotos es 20 segundos')], verbose_name='Tiempo entre fotos (segundos)'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='tiempo_visualizacion_foto',
            field=models.IntegerField(default=2, help_text='Tiempo que se muestra cada foto antes de continuar', validators=[django.core.validators.MinValueValidator(1, message='El tiempo mínimo de visualización es 1 segundo'), django.core.validators.MaxValueValidator(10, message='El tiempo máximo de visualización es 10 segundos')], verbose_name='Tiempo de visualización de foto'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='total_fotos',
            field=models.IntegerField(default=0, help_text='Número total de fotos tomadas', verbose_name='Total de fotos'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='total_impresiones',
            field=models.IntegerField(default=0, help_text='Número total de collages impresos', verbose_name='Total de impresiones'),
        ),
        migrations.AddField(
            model_name='photoboothconfig',
            name='total_sesiones',
            field=models.IntegerField(default=0, help_text='Número total de sesiones completadas', verbose_name='Total de sesiones'),
        ),
        migrations.DeleteModel(
            name='PhotoboothSession',
        ),
    ]
