# Generated by Django 5.1.5 on 2025-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_fotografia_invitado_fotografia_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='invitado',
            field=models.ManyToManyField(related_name='fotografias', to='usuarios.invitado'),
        ),
    ]
