# Generated by Django 5.1.5 on 2025-05-12 15:30

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customgroup_alter_fotografia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoriaevento', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('photobook', 'Photobook'), ('foto_tradicional', 'Foto tradicional'), ('video', 'Video'), ('cabina_360', 'Cabina 360'), ('cabina_fotos', 'Cabina fotos'), ('drone', 'Drone'), ('clip_inicio', 'Clip de inicio')], max_length=100, verbose_name='Servicios'),
        ),
    ]
