# Generated by Django 5.1.5 on 2025-05-31 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cliente_apellido_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'La cédula debe tener al menos 5 dígitos')], verbose_name='Cédula'),
        ),
    ]
