# Generated by Django 5.1.5 on 2025-02-23 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_invitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='list_image/')),
                ('descripcion', models.TextField(max_length=100)),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='usuarios.invitado')),
            ],
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
