# Generated by Django 5.1.6 on 2025-02-26 17:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_invitado_fotografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(db_index=True, help_text='Número de cédula o documento de identidad', max_length=20, unique=True, verbose_name='Cédula')),
                ('fechaNacimiento', models.DateField(help_text='Fecha de nacimiento del cliente', verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(help_text='Dirección completa del cliente', max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(db_index=True, help_text='Correo electrónico del cliente', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['cedula'], name='usuarios_cl_cedula_f55efd_idx'), models.Index(fields=['correo'], name='usuarios_cl_correo_179f36_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='usuarios_cl_search__108e6a_gin')],
            },
        ),
    ]
