# Generated by Django 5.1.6 on 2025-04-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_photoboothsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurar_photobooth',
            name='camera_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de cámara seleccionada'),
        ),
    ]
