# Generated by Django 5.1.5 on 2025-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_fotografia_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='invitado',
            field=models.ManyToManyField(null=True, related_name='fotografias', to='usuarios.invitado'),
        ),
    ]
