# Generated by Django 5.1.5 on 2025-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cliente_apellido_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
