# Generated by Django 5.1.6 on 2025-03-04 12:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o título del evento', max_length=200, verbose_name='Nombre del evento')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora programada para el evento', verbose_name='Fecha y hora del evento')),
                ('servicios', multiselectfield.db.fields.MultiSelectField(choices=[('photobook', 'Photobook'), ('foto_tradicional', 'Foto tradicional'), ('video', 'Video'), ('cabina_360', 'Cabina 360'), ('cabina_fotos', 'Cabina fotos'), ('drone', 'Drone'), ('clip_inicio', 'Clip de inicio')], help_text='Servicios contratados para el evento', max_length=100, verbose_name='Servicios')),
                ('direccion', models.CharField(help_text='Dirección completa donde se realizará el evento', max_length=255, verbose_name='Dirección del evento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('cliente', models.ForeignKey(help_text='Cliente asociado al evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='usuarios_ev_fecha_h_e4dd0a_idx'), models.Index(fields=['cliente'], name='usuarios_ev_cliente_4edfc3_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='usuarios_ev_search__de3133_gin')],
            },
        ),
    ]
