# Generated by Django 5.1.6 on 2025-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_photoboothconfig_usb_auto_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothconfig',
            name='tipo_camara',
            field=models.CharField(choices=[('webcam', 'Cámara Web'), ('nikon_dslr', 'Nikon DSLR/Mirrorless'), ('usb_ptp', 'Cámara USB (PTP)'), ('canon_dslr', 'Canon DSLR'), ('sony_camera', 'Sony Camera'), ('windows_camera', 'Cámara Windows (WIA/PTP)')], default='webcam', help_text='Tipo de cámara a utilizar', max_length=20, verbose_name='Tipo de cámara'),
        ),
    ]
