# Generated by Django 5.1.6 on 2025-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_configurar_photobooth_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurar_photobooth',
            name='balance_blancos',
            field=models.CharField(choices=[('auto', 'Automático'), ('cloudy', 'Nublado'), ('sunny', 'Soleado'), ('fluorescent', 'Fluorescente'), ('incandescent', 'Incandescente')], default='auto', max_length=20, verbose_name='Balance de blancos'),
        ),
        migrations.AddField(
            model_name='configurar_photobooth',
            name='resolucion_camara',
            field=models.CharField(choices=[('640x480', '640x480 (VGA)'), ('1280x720', '1280x720 (HD)'), ('1920x1080', '1920x1080 (Full HD)'), ('3840x2160', '3840x2160 (4K)')], default='1280x720', max_length=20, verbose_name='Resolución de cámara'),
        ),
    ]
