# Generated by Django 5.1.5 on 2025-05-31 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'La cédula debe tener al menos 5 dígitos.')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'La dirección debe tener al menos 5 caracteres.')], verbose_name='Dirección'),
        ),
    ]
