# Generated by Django 5.1.5 on 2025-05-28 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_fotografia_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe ser de al menos 2 caracteres')], verbose_name='Nombre'),
        ),
    ]
