# Generated by Django 5.1.6 on 2025-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(help_text='Nombre o título del evento', max_length=100, verbose_name='Nombre del evento'),
        ),
    ]
