# Generated by Django 5.1.6 on 2025-06-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_photoboothconfig_tipo_camara'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Número de WhatsApp del usuario', max_length=20, verbose_name='Número de teléfono')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del usuario')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del usuario')),
                ('status', models.CharField(choices=[('sent_to_device', 'Enviado al dispositivo'), ('data_collected', 'Datos recopilados'), ('whatsapp_sent', 'Enviado por WhatsApp'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='sent_to_device', max_length=20, verbose_name='Estado de la transferencia')),
                ('transfer_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Momento de la transferencia')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la transferencia', verbose_name='Metadatos adicionales')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del dispositivo')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del dispositivo')),
                ('custom_message', models.TextField(blank=True, help_text='Mensaje personalizado enviado con el collage', null=True, verbose_name='Mensaje personalizado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de reenvío')),
                ('collage_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_transfers', to='usuarios.collageresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_transfers', to='usuarios.collagesession')),
            ],
            options={
                'verbose_name': 'Transferencia de WhatsApp',
                'verbose_name_plural': 'Transferencias de WhatsApp',
                'ordering': ['-transfer_timestamp'],
                'indexes': [models.Index(fields=['status'], name='usuarios_wh_status_0696bb_idx'), models.Index(fields=['transfer_timestamp'], name='usuarios_wh_transfe_a69831_idx'), models.Index(fields=['session'], name='usuarios_wh_session_eedf4b_idx')],
            },
        ),
    ]
