# Generated by Django 5.1.6 on 2025-04-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_configurar_photobooth_balance_blancos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collagetemplate',
            name='background_position',
            field=models.CharField(default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='collagetemplate',
            name='background_repeat',
            field=models.CharField(default='no-repeat', max_length=20),
        ),
        migrations.AddField(
            model_name='collagetemplate',
            name='background_size',
            field=models.CharField(default='cover', max_length=20),
        ),
    ]
