# Generated by Django 5.1.5 on 2025-06-01 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cliente_cedula_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='descripcion',
            field=models.TextField(max_length=34, validators=[django.core.validators.MinLengthValidator(5, 'La descripción debe tener al menos 5 caracteres.')]),
        ),
    ]
