# Generated by Django 5.1.6 on 2025-03-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cliente_activo_alter_evento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPhotobooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_bienvenida', models.CharField(default='¡Bienvenidos a nuestro photobooth!', max_length=255)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='photobooth/fondos/')),
                ('color_texto', models.CharField(default='#000000', max_length=7)),
                ('tamano_texto', models.IntegerField(default=24)),
                ('tipo_letra', models.CharField(default='Arial', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('max_fotos', models.IntegerField(choices=[(1, '1 foto'), (2, '2 fotos'), (4, '4 fotos'), (5, '5 fotos')], default=4)),
                ('permitir_personalizar', models.BooleanField(default=True, help_text='Permitir a los usuarios mover y redimensionar fotos')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_photobooth', to='usuarios.evento')),
            ],
        ),
    ]
