# Generated by Django 5.1.5 on 2025-06-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_fotografia_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='invitado',
            new_name='invitados',
        ),
    ]
