# Generated by Django 5.1.6 on 2025-03-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_configuracionphotobooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollageSession',
            fields=[
                ('session_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_sessions', to='usuarios.evento')),
            ],
            options={
                'verbose_name': 'Sesión de Collage',
                'verbose_name_plural': 'Sesiones de Collage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollageResult',
            fields=[
                ('collage_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='collage/results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='usuarios.collagesession')),
            ],
            options={
                'verbose_name': 'Resultado de Collage',
                'verbose_name_plural': 'Resultados de Collage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollageTemplate',
            fields=[
                ('template_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='collage/backgrounds/')),
                ('template_data', models.TextField(help_text='Datos completos de la plantilla en formato JSON')),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_templates', to='usuarios.evento')),
            ],
            options={
                'verbose_name': 'Plantilla de Collage',
                'verbose_name_plural': 'Plantillas de Collage',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='collagesession',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='usuarios.collagetemplate'),
        ),
        migrations.CreateModel(
            name='PhotoboothConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_bienvenida', models.CharField(default='¡Bienvenidos al photobooth!', max_length=200)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='photobooth/fondos/')),
                ('color_texto', models.CharField(default='#000000', max_length=20)),
                ('tamano_texto', models.IntegerField(default=24)),
                ('tipo_letra', models.CharField(default='Arial', max_length=50)),
                ('max_fotos', models.IntegerField(default=4)),
                ('permitir_personalizar', models.BooleanField(default=False)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_config', to='usuarios.evento')),
                ('plantilla_collage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_configs', to='usuarios.collagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField(help_text='Índice del marco en la plantilla')),
                ('image', models.ImageField(upload_to='collage/session_photos/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='usuarios.collagesession')),
            ],
            options={
                'verbose_name': 'Foto de Sesión',
                'verbose_name_plural': 'Fotos de Sesión',
                'ordering': ['session', 'frame_index'],
                'unique_together': {('session', 'frame_index')},
            },
        ),
    ]
