# Generated by Django 5.1.6 on 2025-03-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_collagesession_collageresult_collagetemplate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguracionPhotobooth',
            new_name='Configurar_Photobooth',
        ),
    ]
